apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-s1mp1e-setting
spec:
  forms:
    - group: style
      label: 样式
      formSchema:
        - $formkit: color
          name: background_color
          label: 背景颜色
          value: "#f2f2f2"
    - group: base
      label: 基础设置
      formSchema:
        - $formkit: text
          name: title
          label: 标题
          value: ""
        - $formkit: attachment
          name: logo
          label: logo
          value: ""